### ISSUE TITLE
Semantic segmentation part of the article

### ISSUE THREAD

**Issue by yaoyuan10475** [Gumpest/AvatarKD#2]
Hello, after I saw your article, I was very interested in the semantic segmentation part of Avatar's improved algorithm for CWD, but there is no config for this part in the warehouse. Is it convenient to announce it? Or I didn't find it. I would be very grateful if I could get your reply.

**Comment by Gumpest** [comment]
Dear @yaoyuan10475, the path of the core code is mmrazor/models/losses/akd_cwd.py. Besides, about the segmentation config, you can refer to https://github.com/open-mmlab/mmrazor/blob/0.x/configs/distill/cwd/cwd_cls_head_pspnet_r101_d8_pspnet_r18_d8_512x1024_cityscapes_80k.py. 

Thanks a lot follow AvatarKD and cite it.
